### ISSUE TITLE
ZF2 compatitibility

### ISSUE THREAD

**Issue by chateaux** [heiglandreas/HybridAuth#17]
Hi -

I see HybridAuth has been limited to:    "zendframework/zendframework": ">=2.1,<2.3.x-dev",

Which is causing the following incompatibility errors when the framework is updated:

- org_heigl/hybridauth dev-master requires zendframework/zendframework >=2.1,<2.3.x-dev -> no matching package found.
    - org_heigl/hybridauth dev-master requires zendframework/zendframework >=2.1,<2.3.x-dev -> no matching package found.

Cheers!

**Comment by heiglandreas** [comment]
I'd better update that one then :wink: 

Thanks for reporting!

**Comment by heiglandreas** [comment]
This should now play together nicely with the current ZF2 (2.4)

**Comment by chateaux** [comment]
All working perfectly, thanks!!
